name: Semantic Release

on:
  push:
    branches:
    - master

jobs:
  run_tests:
    uses: ./.github/workflows/ci.yml
    secrets: inherit
    permissions:
      contents: read

  release:
    name: Release
    needs: run_tests
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-release
      cancel-in-progress: false
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        ref: ${{ github.ref_name }}

    - run: git reset --hard ${{ github.sha }}

    - name: Python Semantic Release
      id: release
      uses: python-semantic-release/python-semantic-release@350c48fcb3ffcdfd2e0a235206bc2ecea6b69df0 # v10.5.3
      with:
        git_committer_name: "github-actions[bot]"
        git_committer_email: "github-actions[bot]@users.noreply.github.com"
        changelog: "false"

    - name: Upload dist artifacts
      if: steps.release.outputs.released == 'true'
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

    outputs:
      released: ${{ steps.release.outputs.released }}
      version: ${{ steps.release.outputs.version }}

  publish_to_pypi:
    name: Publish to PyPI
    needs: release
    if: needs.release.outputs.released == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Download dist artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.PYPI_UPLOAD_TOKEN }}
